"""Closed-loop simulation of virtual patients: medication scenario, recording
model, sensing, stimulation policies and outcome metrics, vectorized over a
batch of patients.

Recording: the sensed local field potential is the synaptic part of the STN
mean membrane potential, that is the potential minus its stimulation
component (the stimulation input passed through the same synaptodendritic
dynamics; the model is linear in its inputs, so the split is exact), plus an
aperiodic background with power spectral density
kappa * m_c(20 Hz) * 2 sigma^2 h * (f/20)^-chi, where m_c is the healthy-state
linear spectrum at the patient's delay scale (twin.anchor), sigma the brainstem
noise level and h its hold time; this matches the measurement model used for
anchoring. Sensing runs at 1 kHz: band-pass (causal 4th-order Butterworth,
peak frequency +/- 3 Hz), rectification, pi/2 scaling and a 0.2-s low-pass
give the beta envelope. Policies update every 10 ms; the actuator clips the
command to [0, U_MAX] and limits its slew to U_MAX / 0.25 s.
Outcomes use the synaptic STN potential without background, 13-30 Hz
envelope."""
import numpy as np
from scipy.signal import butter

from .model import Model, IDX
from .linear import fixed_point_one
from .patients import params
from .cohort import severity_params

U_MAX = 10.0          # mV, largest STN stimulation input
RAMP_S = 0.25         # s, time to traverse [0, U_MAX]
R_MAX = U_MAX / RAMP_S
DT = 2e-4
FS = 1000.0
TC = 0.01
TAU_ENV = 0.2
NOISE_HOLD = 1e-3
SEV_UPDATE = 0.01
SEV_KEYS = ("vd1e", "vd2e", "vp2p2", "vee", "vei", "vp2d2", "tp2", "tz", "vsp1", "phin")


def medication(t, onset=20.0, rise=20.0, plateau_end=75.0, fall=30.0):
    """Medication level in [0, 1]: OFF, raised-cosine rise to ON, plateau,
    raised-cosine wearing off (time-compressed dose cycle)."""
    t = np.asarray(t, float)
    up = np.clip((t - onset) / rise, 0, 1)
    dn = np.clip((t - plateau_end) / fall, 0, 1)
    return 0.5 * (1 - np.cos(np.pi * up)) * 0.5 * (1 + np.cos(np.pi * dn))


SCENARIOS = {
    "cycle": dict(T=120.0, m=medication),
    "off": dict(T=60.0, m=lambda t: 0.0 * np.asarray(t, float)),
    "on": dict(T=60.0, m=lambda t: 1.0 + 0.0 * np.asarray(t, float)),
}
BURN = 10.0


def _bandpass(f_lo, f_hi, fs=FS, order=2):
    secs = [butter(order, [lo, hi], btype="band", fs=fs, output="sos") for lo, hi in zip(f_lo, f_hi)]
    return np.stack(secs, axis=-1)


class SOS:
    """Causal cascade of biquads (transposed direct form II), batch-wise."""

    def __init__(self, sos):
        self.sos = sos
        self.z = np.zeros((sos.shape[0], 2, sos.shape[2]))

    def step(self, x):
        y = x
        for k in range(self.sos.shape[0]):
            b0, b1, b2, _, a1, a2 = self.sos[k]
            z = self.z[k]
            out = b0 * y + z[0]
            z[0] = b1 * y - a1 * out + z[1]
            z[1] = b2 * y - a2 * out
            y = out
        return y


def background_noise(n, fs, chi, level20, rng):
    """Aperiodic noise (n samples per column, float32) whose one-sided PSD is
    level20 * (f/20)^-chi, generated by spectral shaping of white noise."""
    B = len(chi)
    X = rng.standard_normal((B, n)).astype(np.float32)
    F = np.fft.rfft(X, axis=1)
    f = np.fft.rfftfreq(n, 1.0 / fs)
    f[0] = f[1]
    shape = (f[None, :] / 20.0) ** (-chi[:, None] / 2.0)
    # white noise of unit variance has one-sided PSD 2/fs
    gain = np.sqrt(level20 * fs / 2.0)[:, None]
    return (np.fft.irfft(F * shape * gain, n=n, axis=1)).astype(np.float32)


def initial_state(pt, s):
    """Unstimulated fixed-point rates (8, B) of patients pt at severity s."""
    p = params(pt, s)
    return np.stack([fixed_point_one({k: float(v[j]) for k, v in p.items()}) for j in range(len(pt))], axis=1)


_REF20 = {}


def healthy_ref20(c):
    """Healthy-state (s = -1) linear STN potential spectrum at 20 Hz per unit
    brainstem noise density, for delay scales c (array); cached per value."""
    from .linear import potential_spectrum
    out = []
    for cc in np.atleast_1d(c):
        key = round(float(cc), 6)
        if key not in _REF20:
            q = {k: float(v[0]) for k, v in severity_params(-1.0).items()}
            q["ct_scale"] = key
            _REF20[key] = potential_spectrum(q, fixed_point_one(q), np.array([20.0]))[0]
        out.append(_REF20[key])
    return np.array(out)


# Policies ----------------------------------------------------------------

class Policy:
    def __init__(self, **p):
        self.p = {k: np.asarray(v, float) for k, v in p.items()}

    def reset(self, B):
        pass


class Continuous(Policy):
    """Constant amplitude a."""

    def target(self, env_rel, u, Tc):
        return np.broadcast_to(self.p["a"], u.shape)


class SingleThreshold(Policy):
    """Ramp towards amplitude a at rate ramp while the envelope exceeds thr
    (relative to the calibrated envelope), towards zero otherwise."""

    def target(self, env_rel, u, Tc):
        step = self.p["ramp"] * Tc
        return np.clip(u + np.where(env_rel > self.p["thr"], step, -step), 0.0, self.p["a"])


class DualThreshold(Policy):
    """Ramp up at rate ramp while the envelope exceeds hi, down while it is
    below lo, hold otherwise, within [a_min, a_max] with a_min = floor * a_max
    (the lower and upper amplitudes of the clinical dual-threshold scheme)."""

    def target(self, env_rel, u, Tc):
        hi = self.p["lo"] + self.p["gap"]
        step = self.p["ramp"] * Tc
        up = env_rel > hi
        dn = env_rel < self.p["lo"]
        lo_amp = self.p["floor"] * self.p["a_max"]
        return np.clip(u + np.where(up, step, 0.0) - np.where(dn, step, 0.0), lo_amp, self.p["a_max"])


POLICIES = {"continuous": Continuous, "single": SingleThreshold, "dual": DualThreshold}


def run(pt, policy, scenario, calib, seed, b_ref, T=None, record=False, lib_ref20=None, probe=None,
        record_lfp=False):
    """Simulate patients pt (DataFrame) under policy.
    calib: dict with per-patient arrays f_peak (Hz) and b_cal (sensed envelope
    scale); b_ref: fixed beta reference of the outcome.
    probe: optional callable t -> command array, replacing the policy
    (calibration protocol). record_lfp returns the sensed signal at 1 kHz.
    Returns a dict of per-patient outcomes."""
    B = len(pt)
    sc = SCENARIOS[scenario]
    if lib_ref20 is None:
        lib_ref20 = healthy_ref20(pt.c.values)
    T = sc["T"] if T is None else T
    rng = np.random.default_rng(seed)
    s_off, s_on = pt.s_off.values, pt.s_on.values
    sev = lambda t: s_off + sc["m"](t) * (s_on - s_off)
    p0 = params(pt, sev(0.0))
    m = Model(p0, B, DT)
    phi0 = calib.get("phi0")
    if phi0 is None:
        phi0 = initial_state(pt, sev(0.0))
    m.reset(phi0)
    # recording background
    n_s = int(round(T * FS))
    level20 = pt.kappa.values * lib_ref20 * 2.0 * pt.noise.values ** 2 * NOISE_HOLD
    bg = background_noise(n_s + 1, FS, calib["chi"], level20, rng)
    f_sense = SOS(_bandpass(calib["f_peak"] - 3.0, calib["f_peak"] + 3.0))
    f_eval = SOS(_bandpass(np.full(B, 13.0), np.full(B, 30.0)))
    env = np.zeros(B)
    env_true = np.zeros(B)
    a_env = 1.0 / (FS * TAU_ENV)
    u = np.zeros(B)
    if policy is not None:
        policy.reset(B)
    n_steps = int(round(T / DT))
    n_sense, n_ctrl, n_sev = int(round(1 / (FS * DT))), int(round(TC / DT)), int(round(SEV_UPDATE / DT))
    hold = int(round(NOISE_HOLD / DT))
    noise = np.zeros(B)
    acc = dict(be=np.zeros(B), u2=np.zeros(B), du=np.zeros(B), relay=np.zeros(B), n=0)
    trace = {k: [] for k in ("t", "env", "env_true", "u", "m")} if record else None
    k_s = 0
    g = pt.g.values
    ab, apb = m.ab, m.apb
    vs, dvs = np.zeros(B), np.zeros(B)
    lfp = np.empty((B, n_s), np.float32) if record_lfp else None
    for n in range(n_steps):
        t = n * DT
        if n % n_sev == 0 and n > 0:
            p = params(pt, sev(t))
            m.set_params({k: p[k] for k in SEV_KEYS})
        if n % hold == 0:
            noise = pt.noise.values * rng.standard_normal(B)
        if n % n_ctrl == 0 and n > 0:
            if probe is not None:
                u_new = probe(t)
            else:
                u_new = policy.target(env / calib["b_cal"], u, TC)
            u_new = np.clip(np.clip(u_new, u - R_MAX * TC, u + R_MAX * TC), 0.0, U_MAX)
            if t >= BURN:
                acc["du"] += np.abs(u_new - u)
            u = u_new
        Qn = m.step(m.q["phin"] + noise, (g * u, 0.0, 0.0))
        # stimulation component of the STN potential (same linear dynamics)
        a0 = ab * (g * u - vs) - apb * dvs
        vs1, dvs1 = vs + DT * dvs, dvs + DT * a0
        a1 = ab * (g * u - vs1) - apb * dvs1
        vs, dvs = vs + 0.5 * DT * (dvs + dvs1), dvs + 0.5 * DT * (a0 + a1)
        if n % n_sense == 0:
            vz = m.V[IDX["z"]] - vs
            obs = vz + bg[:, k_s]
            if record_lfp and k_s < n_s:
                lfp[:, k_s] = obs
            y = f_sense.step(obs)
            env += a_env * (0.5 * np.pi * np.abs(y) - env)
            ye = f_eval.step(vz)
            env_true += a_env * (0.5 * np.pi * np.abs(ye) - env_true)
            if t >= BURN:
                acc["be"] += env_true
                acc["u2"] += u ** 2
                acc["relay"] += Qn[IDX["s"]]
                acc["n"] += 1
            if record and k_s % 20 == 0:
                trace["t"].append(t)
                trace["env"].append(env.copy())
                trace["env_true"].append(env_true.copy())
                trace["u"].append(u.copy())
                trace["m"].append(float(sc["m"](t)))
            k_s += 1
    nacc = max(acc["n"], 1)
    T_eval = nacc / FS
    out = dict(B=acc["be"] / nacc / b_ref, U=acc["u2"] / nacc / U_MAX ** 2, V=acc["du"] / T_eval / R_MAX,
               be_mean=acc["be"] / nacc, relay=acc["relay"] / nacc)
    if record:
        out["trace"] = {k: np.array(v) for k, v in trace.items()}
    if record_lfp:
        out["lfp"] = lfp
    return out


def cost(out, lam=0.5, w_v=0.05):
    """Scenario cost J = B + lam U + w_v V (lower is better)."""
    return out["B"] + lam * out["U"] + w_v * out["V"]
